# -*- coding: utf-8 -*-
"""Raptor-Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h5K7qxURcbte4N4Oyi86u1MAwqQ2u3Ts

RAPTOR TO PYTHON
"""

#area of a circle
pi=3.14
radius=int(input("Enter radius of the circle "))
area=pi*radius**2
print("area of the circle=",area)

#area and perimeter of a triangle
import math 
a=int(input("enter a value"))
b=int(input("enter a value"))
c=int(input("enter a value"))
perimeter=a+b+c
print("perimeter of triangle",perimeter)
s=perimeter/2
area=math.sqrt(s*(s-a)*(s-b)*(s-c))
print("area of triangle",area)

#palindrome
n=int(input("Enter a number"))
rev=0
p=n
while n>0:
 rem=n%10
 rev=rev*10+rem
 n=n//10
if p==rev:
  print("The number is palindrome")
else: 
  print("The number is not a palindorme")

#finding average of 3 numbers
x=int(input("enter a number"))
y=int(input("enter a number"))
z=int(input("enter a number"))
avg=(x+y+z)/3
print('average value is',avg)

#time conversion
import math
time=int(input("Enter a time in seconds"))
hour=math.floor(time/3600)
time2=hour*3600
time3=time-time2
minutes=math.floor(time3/60)
time4=minutes*60
seconds=time3-time4
print("hour=",hour)
print("minutes=",minutes)
print("seconds=",seconds)

#interchange 2 unequal number without using third variable
a=int(input("Enter number a"))
b=int(input("Enter number b"))
a=a+b
b=a-b
a=a-b
print("a=",a)
print("b=",b)

#arithmetic operations
import math
a=int(input("Enter number a"))
b=int(input("Enter number b"))
sum=a+b
difference=a-b
pro=a*b
quotient=math.floor(a/b)
remainder=a mod b

#factors of n
n=3
f=1
while f<=n:
  if n%f==0:
    print(f)   
  f=f+1

"""#prime
c=0
n=int(input("Enter a number"))
f=2
while f<=n//2:
  if n%f==0:
    c=c+1
    break
  f=f+1
if c==0:
    print(n,"is prime")
else:
    print(n,"is not prime")
        
"""

#amstrong number
n=int(input("Enter a number"))
t=n
count=0
while n>0:
  count=count+1
  n=n//10
x=t
r=0
sum=0
while t>0:
  r=t%10
  sum=sum+(r**count)
  t=t//10
if sum==x:
  print("This is an amstrong number") 
else:
  print("This is not an amstrong number")

#a number is a multiple of another
a=int(input("Enter a number"))
b=int(input("Enter a number"))
if a>b:
  if a%b==0:
    print("b is multiple of a")
  else:
    print("b is not a multiple of a")   
else:
  if b%a==0:
    print("a is multiple of b")
  else:
    print("a is not a multiple of b")

# 2 digit number check
n=int(input("Enter a number"))
if (n>9 and n<-100):
  print("The number is two digit")
else:
  print("The number is not two digit")

#greatest of three numbers
a=int(input("Enter a number"))
b=int(input("Enter a number"))
c=int(input("Enter a number"))
if a>b:
  if a>c:
    print("a is the greatest number")
  else:
    print("c is the greatest number")
else: 
  if b>c:
    print("b is the greatest")
  else:
    print("c is the greatest")

#positive or negative check
n=int(input("Enter a number"))
if n==0:
  print("n is neither positive nor negative")
if n<0:
  print("n is a negative integer")  
else:
  print("n is a  positive integer")

#distance between two points
a=int(input("Enter a point"))
b=int(input("Enter a point"))
if a>b:
  s=a-b
  print("distance=",s)
else:
  s=b-a
  print("distance=",s)

#largest among two numbers
a=int(input("Enter a number"))
b=int(input("Enter a number"))
if a>b:
  print("a is greater than b")
elif b>a:
  print("b is greater than a")

#Convert days into year,month and days
t=int(input("Enter the number of days"))
year=t//365
month=(t%365)//30
days=(t-(year*365)-(month*30))
print("year:",year)
print("month:",month)
print("day:",days)

#reverse a number
n=int(input("Enter a number"))
rev=0
x=n
while n>0:
  rem=n%10
  rev=rev*10+rem
  n=n//10
print("The reversed number:",rev)

#smallest of three numbers
a=int(input("Enter a number"))
b=int(input("Enter a number"))
c=int(input("Enter a number"))
if a>b and b>c:
  print(c,"is the smallest number ")
elif a>b and c>b:
  print(b,"is the smallest number") 
else:
  print(a,"is the smallest number")

#sum of n natural numbers
n=int(input("Enter the nmuber"))
sum=(n*(n+1))/2
print("sum of",n, "natural number is",sum)

#sum of factors of number
a=int(input("Enter a number"))
i=1
sum=0
while i<=a/2:
  if a%i==0:
    sum=sum+i
  i=i+1
sum=sum+a
print("sum of factors of ", a ," is ",sum)

#arithmetic sequence
a=int(input("Enter the first element"))
d=int(input("Enter the commen difference"))
n=int(input("Enter the number of terms required"))
an=a
while n>0:
  print(an)
  n=n-1
  an=an+d

#first 'n' odd numbers
n=int(input("Enter the number of integers reqiured"))
i=1
while i<n*2:
  print(i)
  i=i+2

#factorial of a number
num=int(input("Enter the integer"))
i=1
pro=i
if num>1:
  while i<=num:
    pro=pro*i
    i=i+1
  print("Factorial of ",num, " is ",pro)
elif  num==0 or num==1:
 print("Factorial of ",num, " is ",1)

#nature of quadratic equation
a=int(input("Enter 'a' from the equation"))
b=int(input("Enter 'b' from the equation"))
c=int(input("Enter 'c' from the equation"))
d=(b*b)-(4*a*c) 
if d>=0:
  print("The equation real roots")
else:
  print("The eqation has no real roots")

#fibonacci series
n=int(input("Enter the number of terms"))
if n==1:
  print(0)
elif n==2:
  print(0,",",1) 
elif n>2:
  n1=0
  n2=1
  print(n1)
  print(n2)
  while n>2:
    n3=n2+n1
    n1=n2
    n2=n3
    n=n-1
    print(n3)

#x^n using loops
x=int(input("Enter a number"))
n=int(input("Enter the power "))
i=1
d=x
while i<n:
  d=d*x
  i=i+1
print(d)

#GCD of two numbers
a=int(input("Enter a number"))
b=int(input("Enter a number"))
i=1
d=i
while i<=a/2 or i<=b/2:
  if a%i==0 and b%i==0:
    d=i
  i=i+1
print("GCD of ",a," & ",b," is ",d)

#decimal equivalent of a binary  number
binary=int(input("Enter a binary number"))
i=0
x=binary
n=0
while x>0:
  n=n+(x%10)*(2**i)
  x=x//10
  i=i+1
print("Decimal value is ",n)

#sum of arithmetic seires upto n terms
a=int(input("Enter the first element"))
d=int(input("Enter the commen difference"))
n=int(input("Enter the number of terms required"))
an=a
sum=0
while n>0:
  sum=sum+an
  n=n-1
  an=an+d
print("sum=",sum)

#automorphic number
num=int(input("Enter a number"))
s=num
p=0
r=0
while s>0:
  p=p*10+s%10
  s=s//10
  r=r+1
s=num*num
p=s%(10**r)
if num==p:
  print("Given number is automorphic")
else:
  print("Given number is not automorphic")